from pynput.keyboard import Key


POSE_MODEL_PATH = "pose_landmarker_full.task"
HAND_MODEL_PATH = "hand_landmarker.task"
FACE_MODEL_PATH = "face_landmarker.task"

UPPER_BODY_CONNECTIONS = [
    (11, 12),
    (11, 13),
    (13, 15),
    (12, 14),
    (14, 16),
]

UPPER_BODY_LANDMARKS = [
    0,
    11,
    12,
    13,
    14,
    15,
    16,
]

HAND_CONNECTIONS = [
    (0, 1),
    (1, 2),
    (2, 3),
    (3, 4),
    (0, 5),
    (5, 6),
    (6, 7),
    (7, 8),
    (5, 9),
    (9, 10),
    (10, 11),
    (11, 12),
    (9, 13),
    (13, 14),
    (14, 15),
    (15, 16),
    (13, 17),
    (17, 18),
    (18, 19),
    (19, 20),
    (0, 17),
]

FINGER_LANDMARKS = {
    "index": (5, 6, 7, 8),
    "middle": (9, 10, 11, 12),
    "ring": (13, 14, 15, 16),
    "pinky": (17, 18, 19, 20),
}

CONTROL_HAND = "PHYSICAL_LEFT"
ACTION_HAND = "PHYSICAL_RIGHT"

MEDIAPIPE_LABELS_MATCH_PHYSICAL_HANDS = False
INVERT_HORIZONTAL_MOVEMENT = False

HEAD_CONTROL_STARTS_ON = False
HEAD_YAW_DEADZONE_DEGREES = 5.0
HEAD_PITCH_DEADZONE_DEGREES = 4.0
HEAD_YAW_STOP_DEGREES = 3.5
HEAD_PITCH_STOP_DEGREES = 2.8
HEAD_SMOOTHING_ALPHA = 0.35
HEAD_YAW_SENSITIVITY = 1.8
HEAD_PITCH_SENSITIVITY = 1.6
HEAD_MAX_RELATIVE_YAW = 35.0
HEAD_MAX_RELATIVE_PITCH = 25.0
MAX_MOUSE_X = 26
MAX_MOUSE_Y = 22
INVERT_HEAD_YAW = False
INVERT_HEAD_PITCH = False
USE_WINDOWS_GAME_MOUSE = True
MOUSEEVENTF_MOVE = 0x0001

ENABLE_ACTION_OUTPUT = True
ACTION_HISTORY_LENGTH = 5
ACTION_ENTER_FRAMES = 3
ACTION_UNKNOWN_EXIT_FRAMES = 2
ACTION_PINCH_ENTER_THRESHOLD = 0.38
ACTION_PINCH_EXIT_THRESHOLD = 0.48
ACTION_FINGER_EXTENDED_MIN_ANGLE = 150
ACTION_FINGER_CURLED_MAX_ANGLE = 125
JUMP_COOLDOWN_SECONDS = 0.55
JUMP_HOLD_SECONDS = 0.08

INDEX_MIN_VECTOR_LENGTH = 0.045
INDEX_UP_RIGHT_MIN_ANGLE = 0
INDEX_UP_RIGHT_MAX_ANGLE = 78
INDEX_UP_MIN_ANGLE = 62
INDEX_UP_MAX_ANGLE = 118
INDEX_UP_LEFT_MIN_ANGLE = 102
INDEX_UP_LEFT_MAX_ANGLE = 180
INDEX_DIAGONAL_RATIO = 0.28

PINCH_DISTANCE_RATIO = 0.35
THUMB_EXTENDED_MIN_ANGLE = 125
THUMB_EXTENDED_DISTANCE_RATIO = 0.70
THUMB_AWAY_FROM_INDEX_RATIO = 0.42
THUMB_AWAY_FROM_FINGERS_RATIO = 0.32

MOVEMENT_STATES_TO_KEYS = {
    "NEUTRAL": set(),
    "W": {"w"},
    "W+A": {"w", "a"},
    "W+D": {"w", "d"},
    "A": {"a"},
    "D": {"d"},
    "S": {"s"},
    "SPRINT": {"w", Key.ctrl_l},
}
